export default {
    "nav.home": "Home",
    "nav.ideology": "Ideology",
    "nav.service": "Service",
    "nav.team": "Our team",
    "nav.contact": "Contact",
    "header.title":"BeneCare",
    "header.subtitle":"We ensure that elderly people receive the right care at the right time.",
    "homepage.introduction_title":"BeneCare – Smart Support for Care Work and Everyday Wellbeing",
    "homepage.introduction_p1" : "BeneCare is designed for healthcare professionals — including elderly care staff, nurses, doctors, and physiotherapists — as well as private users who want to monitor the wellbeing of their loved ones safely and unobtrusively.",
    "homepage.introduction_p2": "The service provides round-the-clock monitoring without wearable devices, making both professional care and everyday support more efficient and meaningful. BeneCare uses sensor technology and intelligent algorithms to model a person’s daily rhythm and behavior. ",
    "homepage.introduction_p3" :"This data helps detect changes in health, wellbeing, functional ability, and cognition — enabling timely responses before urgent care is needed.",
    "service.privacyTitle": "We Keep Personal Data Safe",
    "service.privacyText": "The analyses produced by BeneCare service are available to the senior, their relatives, and care staff through the web service or as printouts. The use of the service and data collection are always based on the person's consent. The collected personal data is not used or transmitted for any purpose other than related to the use of the service. In accordance with data protection law, the senior has the right to their own personal data and can request deletion of their personal data or termination of the service at any time.",
  
    "selector.title": "Choose Customer Type",
    "selector.subtitle": "We tailor our services to your needs",
    "selector.private.title": "Private Customers",
    "selector.private.description": "Secure your loved one's wellbeing and monitoring at home",
    "selector.company.title": "Business Customers",
    "selector.company.description": "Improve care efficiency and enhance service quality",
    // Carousel
    "carousel.elderly.title": "Safe daily life for the elderly",
    "carousel.elderly.desc": "BeneCare supports independent living and provides a sense of security in everyday life.",
    "carousel.family.title": "Peace of mind for families",
    "carousel.family.desc": "Families can monitor their loved ones' well-being and receive up-to-date information about their health.",
    "carousel.nurse.title": "Professional care work",
    "carousel.nurse.desc": "Healthcare staff receive accurate information about residents' functional capacity and can respond to changes quickly.",
    "carousel.assistant.title": "Smart technology assistance",
    "carousel.assistant.desc": "The BeneCare system provides an easy-to-use platform for managing and analyzing all information.",
    // Features
    "features.title": "What does BeneCare monitor?",
    "features.subtitle": "Our service provides continuously updated information about a person's functional capacity and well-being",
    "features.activity.title": "Activity Monitoring",
    "features.activity.desc": "Time spent in rooms, indoor and outdoor movement, daily activity levels",
    "features.sleep.title": "Sleep Quality",
    "features.sleep.desc": "Amount, quality and timing of sleep and rest. Changes in nighttime behavior",
    "features.hygiene.title": "Hygiene Monitoring",
    "features.hygiene.desc": "Shower usage and sink activity. Identification of changes in hygiene care",
    "features.wc.title": "Bathroom Visits",
    "features.wc.desc": "Number, timing and duration of bathroom visits. Detection of increased frequency",
    "features.health.title": "Health Metrics",
    "features.health.desc": "Weight, BMI, blood pressure and other health metrics integrated into the system",
    "features.alerts.title": "Alerts",
    "features.alerts.desc": "Emergency bracelet for immediate assistance. All events are logged in the system",
      // How It Works
    "how.title": "How does BeneCare work?",
    "how.subtitle": "A simple and effective process that requires no action from the individual",
    "how.step1.title": "Installation",
    "how.step1.desc": "Unobtrusive sensors are installed in the person's home without disrupting daily life",
    "how.step2.title": "Data Collection",
    "how.step2.desc": "Sensors automatically collect information about daily activities",
    "how.step3.title": "Analysis",
    "how.step3.desc": "Sophisticated algorithms identify activities and model behavior patterns",
    "how.step4.title": "Reporting",
    "how.step4.desc": "Caregivers, doctors and family members receive up-to-date information about functional capacity",
    
  };