export default {
    "nav.home": "Home",
    "nav.ideology": "Ideology",
    "nav.service": "Service",
    "nav.team": "Our team",
    "nav.contact": "Contact",
    "header.title":"BeneCare",
    "header.subtitle":"We ensure that elderly people receive the right care at the right time.",
    "homepage.introduction_title":"Smart Support for Care Work and Everyday Wellbeing",
    "homepage.introduction_p1" : "BeneCare is designed for healthcare professionals including elderly care staff, nurses, doctors, and physiotherapists  as well as private users who want to monitor the wellbeing of their loved ones safely and unobtrusively.",
    "homepage.introduction_p2": "The service provides round-the-clock monitoring without wearable devices, making both professional care and everyday support more efficient and meaningful. BeneCare uses sensor technology and intelligent algorithms to model a person’s daily rhythm and behavior. ",
    "homepage.introduction_p3" :"This data helps detect changes in health, wellbeing, functional ability, and cognition  enabling timely responses before urgent care is needed.",
    "service.privacyTitle": "We Keep Personal Data Safe",
    "service.privacyText": "The analyses produced by BeneCare service are available to the senior, their relatives, and care staff through the web service or as printouts. The use of the service and data collection are always based on the person's consent. The collected personal data is not used or transmitted for any purpose other than related to the use of the service. In accordance with data protection law, the senior has the right to their own personal data and can request deletion of their personal data or termination of the service at any time.",
  
    "selector.title": "Choose Customer Type",
    "selector.subtitle": "We tailor our services to your needs",
    "selector.private.title": "Private Customers",
    "selector.private.description": "Secure your loved one's wellbeing and monitoring at home",
    "selector.company.title": "Business Customers",
    "selector.company.description": "Improve care efficiency and enhance service quality",
    "common.readMore":"Read more",
    "readMore.description":"Learn more about our services and how we offer a unique way to analyze life.",
    
    // Carousel
    "carousel.elderly.title": "Safe daily life for the elderly",
    "carousel.elderly.desc": "BeneCare supports independent living and provides a sense of security in everyday life.",
    "carousel.family.title": "Peace of mind for families",
    "carousel.family.desc": "Families can monitor their loved ones' well-being and receive up-to-date information about their health.",
    "carousel.nurse.title": "Professional care work",
    "carousel.nurse.desc": "Healthcare staff receive accurate information about residents' functional capacity and can respond to changes quickly.",
    "carousel.assistant.title": "Smart technology assistance",
    "carousel.assistant.desc": "The BeneCare system provides an easy-to-use platform for managing and analyzing all information.",
    // service
    "service.heading.intro": "Functionality assessment",
    "service.heading.title": "BeneCare",
    "features.title": "What does BeneCare monitor?",
    "features.subtitle": "Our service provides continuously updated information about a person's functional capacity and well-being",
    "features.activity.title": "Activity Monitoring",
    "features.activity.desc": "Time spent in rooms, indoor and outdoor movement, daily activity levels",
    "features.sleep.title": "Sleep Quality",
    "features.sleep.desc": "Amount, quality and timing of sleep and rest. Changes in nighttime behavior",
    "features.hygiene.title": "Hygiene Monitoring",
    "features.hygiene.desc": "Shower usage and sink activity. Identification of changes in hygiene care",
    "features.wc.title": "Bathroom Visits",
    "features.wc.desc": "Number, timing and duration of bathroom visits. Detection of increased frequency",
    "features.health.title": "Health Metrics",
    "features.health.desc": "Weight, BMI, blood pressure and other health metrics integrated into the system",
    "features.alerts.title": "Alerts",
    "features.alerts.desc": "Emergency bracelet for immediate assistance. All events are logged in the system",
      // How It Works
    "how.title": "How does BeneCare work?",
    "how.subtitle": "A simple and effective process that requires no action from the individual",
    "how.step1.title": "Installation",
    "how.step1.desc": "Unobtrusive sensors are installed in the person's home without disrupting daily life",
    "how.step2.title": "Data Collection",
    "how.step2.desc": "Sensors automatically collect information about daily activities",
    "how.step3.title": "Analysis",
    "how.step3.desc": "Sophisticated algorithms identify activities and model behavior patterns",
    "how.step4.title": "Reporting",
    "how.step4.desc": "Caregivers, doctors and family members receive up-to-date information about functional capacity",
    // Private Customer Page
    "private.hero.title": "Secure Your Loved One's Wellbeing",
    "private.hero.subtitle": "BeneCare provides unobtrusive monitoring and security for elderly living at home",
    "private.hero.cta": "Contact Us",
    "private.benefits.title": "Why BeneCare for Private Customers?",
    "private.benefits.peace.title": "Peace of Mind",
    "private.benefits.peace.text": "You can trust that your loved one is safe with 24/7 monitoring",
    "private.benefits.safety.title": "Safety",
    "private.benefits.safety.text": "Automatic alert in exceptional situations - help arrives on time",
    "private.benefits.response.title": "Quick Response",
    "private.benefits.response.text": "Immediate notification of potential issues to family and caregivers",
    "private.benefits.family.title": "Family Support",
    "private.benefits.family.text": "The whole family can easily monitor their loved one's wellbeing",
    
    // Company Customer Page
    "company.hero.title": "Improve Care Efficiency",
    "company.hero.subtitle": "BeneCare helps care professionals work more efficiently and improve service quality",
    "company.hero.cta": "Request Quote",
    "company.benefits.title": "Why BeneCare for Companies?",
    "company.benefits.efficiency.title": "Efficiency",
    "company.benefits.efficiency.text": "Reduce unnecessary visits and optimize work shifts",
    "company.benefits.cost.title": "Cost Savings",
    "company.benefits.cost.text": "Significant savings in personnel costs",
    "company.benefits.quality.title": "Quality Advantage",
    "company.benefits.quality.text": "Improve service quality with real-time information",
    "company.benefits.data.title": "Data-Driven",
    "company.benefits.data.text": "Make decisions based on reliable data",
    //Conatct
    "contact.form.title": "Contact us",
    "contact.form.type": "I'm interested in:",
    "contact.form.type.general": "General contact",
    "contact.form.type.assessment": "Functionality assessment",
    "contact.form.firstName": "First name",
    "contact.form.lastName": "Last name",
    "contact.form.email": "Email",
    "contact.form.phone": "Phone number (optional)",
    "contact.form.organization": "Organization (optional)",
    "contact.form.role": "Your role (optional)",
    "contact.form.message": "Write your message...",
    "contact.form.submit": "Send",
    "contact.form.successH1": "Thank you for contacting us!",
    "contact.form.successP": "We will get back to you within 24 hours",
    "contact.form.successB": "Close",
    "contact.company": "Benete Ltd",
    "contact.address1": "Tykistökatu 4b",
    "contact.address2": "20520 Turku, Finland",
    "contact.floor": "(5th floor)",
    "contact.ceo": "Kari Bäckman, CEO",
    "contact.phone": "+358 50 052 4514",
    "contact.email": "kari.backman@benete.com",
    "contact.heading.intro": "Let’s talk",
    "contact.heading.title": "How can we help?",

   // Ideology Page
    "ideology.hero.subtitle": "As a care expert",
    "ideology.hero.title1": "Makes everyday life easier",
    "ideology.hero.title1b": "and increases security",
    "ideology.hero.title2": "Brings peace of mind",
    "ideology.hero.title2b": "to families and loved ones",
    "ideology.hero.title3": "Supports active",
    "ideology.hero.title3b": "and independent living for seniors",
    "ideology.title":"On your terms",
    "hero.subtitleLines": [
  [
    { "text": "Individual", "color": "black" },
    { "text": "independence", "color": "blue" }
  ],
  [
    { "text": "Digital", "color": "black" },
    { "text": "dignity", "color": "blue" }
  ],
  [
    { "text": "Valuable", "color": "black" },
    { "text": "life", "color": "blue" }
  ]
],
    "ideology.values.care": "Caring",
    "ideology.values.careDesc": "Every person deserves attention, warmth, and individualized care",
    "ideology.values.safety": "Security",
    "ideology.values.safetyDesc": "Reliable technology and 24/7 monitoring ensure peace of mind",
    "ideology.values.quality": "Quality",
    "ideology.values.qualityDesc": "We are committed to the highest quality in everything we do",
    "ideology.section1.title": "Insights from daily routines",
    "ideology.section1.p1": "Simple daily activities create the rhythm of our everyday life, such as cooking, rest, and personal hygiene. These are part of our normal lives, but they also have a greater significance than we think. Combined and analyzed, they provide valuable insights into our physical and emotional well-being.",
    "ideology.section1.p2": "With the BeneCare service, it is possible to identify changes in functional capacity and cognition at an early stage. Unlike general health and wellness services, we analyze a person's life holistically, covering much more than just physiological data.",
    "ideology.section2.title": "Living environment",
    "ideology.section2.p1": "The living environment is known to have a great impact on our well-being and can also tell a lot about our daily life. The use of smart technologies is constantly increasing and it is only a matter of time before our homes are equipped with various sensor technologies enabling real-time life monitoring.",
    "ideology.section2.p2": "BeneCare service's sophisticated algorithms recognize a person's daily activities, model behaviors in their own living environment, and assess possible changes in functional capacity. By observing and analyzing daily activities, harmful changes in functional capacity can be detected at a much earlier stage than is possible with conventional methods.",
    "ideology.section3.title": "Active aging",
    "ideology.section3.p1": "Quality of life improves when a person can function independently in their own familiar environment. It creates a sense of security and independence from others. The foundation of active aging is one's own activity and motivation for life.",
    "ideology.section3.p2": "Early identification of changes in functional capacity and cognitive disorders helps in providing early and precise care. This has a great impact on people's lives, adding active and independent days to life. Enabling gentle care and cherishing the sense of independence are our key goals.",
    "ideology.section3.p3": "As a result of our activities, social and healthcare benefits significantly from reduced elderly care costs and new, more effective services.",
    "ideology.section4.title": "MyData",
    "ideology.section4.p1": "Data collected from individuals is extremely sensitive. Our service enables our customers to have full access and control over their own data. Our service complies with the latest data protection and information security requirements, taking these into account already in the design of services, together with our own ethical data and digital dignity principles.",
    "ideology.section5.title": "Our values",
    "ideology.section5.p1": "Personal changes in functional capacity are usually not monitored or recorded until it is too late and a diagnosis has been given. Many people are dependent on others to get through the day, which weakens their sense of independence. It is important to recognize what individual independence means for each person.",
    "ideology.section5.p2": "With our service, it is possible to identify functional and memory-related disorders as early as possible and start the necessary treatment measures as early as possible.",
    // Benefits
    "benefits.title": "Benefits for all parties",
    "benefits.subtitle": "BeneCare improves the quality of care and supports the well-being of elderly people",
    "benefits.caregivers": "For Caregivers",
    "benefits.caregivers.1": "More efficient and meaningful care work",
    "benefits.caregivers.2": "Earlier intervention in problems",
    "benefits.caregivers.3": "More precise response to residents' needs",
    "benefits.caregivers.4": "24/7 secure monitoring",
    "benefits.elderly": "For the Elderly",
    "benefits.elderly.1": "Normal daily life without intrusive devices",
    "benefits.elderly.2": "No wearable technology",
    "benefits.elderly.3": "Better quality of life",
    "benefits.elderly.4": "Sense of security",
    "benefits.family": "For Families & Professionals",
    "benefits.family.1": "Up-to-date information on functional capacity",
    "benefits.family.2": "Early detection of emerging problems",
    "benefits.family.3": "Data-driven care decisions",
    "benefits.family.4": "Transparent reporting",
    
    // Funding
    "funding.horizon.title": "Horizon 2020 Research",
    "funding.horizon.text": "Benete Oy has received funding from the European Union's Horizon 2020 research and innovation programme under grant agreement No 877503.",
    "funding.ely.title": "ELY Funding",
    "funding.ely.text": "Benete Oy has received funding from the Centre for Economic Development, Transport and the Environment for the BNT-MDR project. The project involves the further development of Benete Oy's elderly functional capacity analysis service.",
    


    


  };