export default{
   "navHome": "Koti",
    "navIdeology": "Ideologia",
    "navService": "Palvelu",
    "navTeam": "Tiimi",
    "navContact": "Yhteystiedot",
    "headerTitle":"BeneCare",
    "headerSubtitle":"Varmistamme, että ikäihmiset saavat oikeanlaista hoitoa oikea-aikaisesti.",
    "homepageIntroductionTitle":"Älykäs tuki hoitotyöhön ja arjen hyvinvointiin",
    "homepageIntroductionP1" : "BeneCare on kehitetty hoitotyön ammattilaisille  sekä yksityiskäyttäjille, jotka haluavat seurata läheistensä hyvinvointia turvallisesti ja huomaamattomasti.",
    "homepageIntroductionP2": "Palvelu tarjoaa ympärivuorokautisen seurannan ilman puettavia laitteita, tehden hoitotyöstä ja arjen huolenpidosta tehokkaampaa ja mielekkäämpää. BeneCare hyödyntää sensoriteknologiaa ja älykkäitä algoritmeja mallintaakseen henkilön päivittäistä rytmiä ja toimintatapoja. ",
    "homepageIntroductionP3" :"Näiden tietojen avulla voidaan havaita muutoksia terveydessä, hyvinvoinnissa, toimintakyvyssä ja kognitiossa  ja reagoida ajoissa ennen kuin tilanne vaatii akuuttia hoitoa.",
    "servicePrivacyTitle": "Pidämme henkilötiedot turvassa",
    "servicePrivacyText": "BeneCare -palvelun tuottamat analyysit ovat seniorin, hänen omaistensa ja hoitohenkilökunnan nähtävissä verkkopalvelun kautta tai tulosteena. Palvelun käyttö ja datan kerääminen perustuvat aina henkilön suostumukseen. Kerättyä henkilötietoa ei käytetä tai välitetä muuhun kuin palvelun käyttöön liittyvään tarkoitukseen. Tietosuojalain mukaisesti seniorilla on oikeus omiin henkilötietoihinsa ja hän voi pyytää henkilötietojensa poistamista tai palvelun lopettamista milloin tahansa.",
    
   "selectorTitle": "Valitse asiakastyyppi",
  "selectorSubtitle": "Räätälöimme palvelumme tarpeidesi mukaan",
  "selectorPrivateTitle": "Yksityisasiakkaat",
  "selectorPrivateDescription": "Turvaa läheisesi hyvinvointi ja seuranta kotona",
  "selectorCompanyTitle": "Yritysasiakkaat",
  "selectorCompanyDescription": "Tehosta hoitotyötä ja paranna palvelun laatua",

  "commonReadMore": "Lue lisää",
  "readMoreDescription": "Lue lisää palveluistamme ja miten tarjoamme ainutlaatuisen tavan analysoida elämää.",

  "footerFollowUs": "Seuraa meitä",
  "footerPrivacy": "Yksityisyys",
  "footerTerms": "Tietosuoja",

  "carouselElderlyTitle": "Turvallinen arki ikäihmisille",
  "carouselElderlyDesc": "BeneCare tukee itsenäistä asumista ja antaa turvallisuuden tunteen päivittäisessä elämässä.",
  "carouselFamilyTitle": "Mielenrauha omaisille",
  "carouselFamilyDesc": "Perheet voivat seurata läheistensä vointia ja saada ajantasaista tietoa heidän hyvinvoinnistaan.",
  "carouselNurseTitle": "Ammattitaitoinen hoitotyö",
  "carouselNurseDesc": "Hoitohenkilöstö saa tarkat tiedot asukkaiden toimintakyvystä ja voi reagoida muutoksiin nopeasti.",
  "carouselAssistantTitle": "Älykäs teknologia avuksi",
  "carouselAssistantDesc": "BeneCare-järjestelmä tarjoaa helppokäyttöisen alustan kaiken tiedon hallintaan ja analysointiin.",

  "serviceHeadingIntro": "Toimintakyvyn arviointi",
  "serviceHeadingTitle": "BeneCare",

  "featuresTitle": "Mitä BeneCare seuraa?",
  "featuresSubtitle": "Palvelumme tarjoaa jatkuvasti päivittyvää tietoa henkilön toimintakyvystä ja hyvinvoinnista",
  "featuresActivityTitle": "Aktiivisuuden seuranta",
  "featuresActivityDesc": "Huoneessa vietetty aika, liikkuminen sisällä ja ulkona, päivittäinen aktiivisuus",
  "featuresSleepTitle": "Unen laatu",
  "featuresSleepDesc": "Unen ja levon määrä, laatu ja ajankohdat. Yöllisen käyttäytymisen muutokset",
  "featuresHygieneTitle": "Hygienian seuranta",
  "featuresHygieneDesc": "Suihkussa käynti ja pesualtaan käyttö. Hygienian hoidon muutosten tunnistus",
  "featuresWcTitle": "WC-käynnit",
  "featuresWcDesc": "WC-käyntien määrä, ajankohdat ja kesto. Tihentyneiden käyntien havaitseminen",
  "featuresHealthTitle": "Terveysmittarit",
  "featuresHealthDesc": "Paino, BMI, verenpaine ja muut terveysmittarit integroituna järjestelmään",
  "featuresAlertsTitle": "Hälytykset",
  "featuresAlertsDesc": "Hälytysranneke akuutin avun saamiseksi. Kaikki tapahtumat kirjautuvat järjestelmään",


     "howTitle": "Kuinka BeneCare toimii?",
  "howSubtitle": "Yksinkertainen ja tehokas prosessi, joka ei vaadi toimenpiteitä henkilöltä",
  "howStep1Title": "Asennus",
  "howStep1Desc": "Huomaamattomat sensorit asennetaan henkilön asuntoon ilman häiriötä arkeen",
  "howStep2Title": "Tiedon keruu",
  "howStep2Desc": "Sensorit keräävät tietoa päivittäisestä toiminnasta automaattisesti",
  "howStep3Title": "Analysointi",
  "howStep3Desc": "Sofistikoituneet algoritmit tunnistavat toimintoja ja mallintavat toimintatapoja",
  "howStep4Title": "Raportointi",
  "howStep4Desc": "Hoitajat, lääkärit ja omaiset saavat ajankohtaista tietoa toimintakyvystä",

  "privateHeroTitle": "Turvaa läheisesi hyvinvointi",
  "privateHeroSubtitle": "BeneCare tarjoaa huomaamattoman seurannan ja turvaa ikääntyville kotona asumiseen",
  "privateHeroCta": "Ota yhteyttä",
  "privateBenefitsTitle": "Miksi BeneCare yksityisasiakkaille?",
  "privateBenefitsPeaceTitle": "Mielenrauha",
  "privateBenefitsPeaceText": "Voit luottaa, että läheisesi on turvassa 24/7 seurannan ansiosta",
  "privateBenefitsSafetyTitle": "Turvallisuus",
  "privateBenefitsSafetyText": "Automaattinen hälytys poikkeustilanteissa - apu tulee ajoissa",
  "privateBenefitsResponseTitle": "Nopea reagointi",
  "privateBenefitsResponseText": "Välitön tieto mahdollisista ongelmista omaisille ja hoitajille",
  "privateBenefitsFamilyTitle": "Perheen tuki",
  "privateBenefitsFamilyText": "Koko perhe voi seurata läheisen vointia helposti",

  "companyHeroTitle": "Tehosta hoitotyötä",
  "companyHeroSubtitle": "BeneCare auttaa hoitotyön ammattilaisia toimimaan tehokkaammin ja parantamaan palvelun laatua",
  "companyHeroCta": "Pyydä tarjous",
  "companyBenefitsTitle": "Miksi BeneCare yrityksille?",
  "companyBenefitsEfficiencyTitle": "Tehokkuus",
  "companyBenefitsEfficiencyText": "Vähennä turhia käyntejä ja optimoi työvuorot",
  "companyBenefitsCostTitle": "Kustannussäästöt",
  "companyBenefitsCostText": "Merkittävät säästöt henkilöstökustannuksissa",
  "companyBenefitsQualityTitle": "Laatuetu",
  "companyBenefitsQualityText": "Paranna palvelun laatua reaaliaikaisella tiedolla",
  "companyBenefitsDataTitle": "Datalähtöisyys",
  "companyBenefitsDataText": "Tee päätökset luotettavan datan pohjalta",

  "contactFormTitle": "Ota yhteyttä",
  "contactFormType": "Olen kiinnostunut:",
  "contactFormTypeGeneral": "Yleinen yhteydenotto",
  "contactFormTypeAssessment": "Toimintakyvyn arviointi",
  "contactFormFirstName": "Etunimi",
  "contactFormLastName": "Sukunimi",
  "contactFormEmail": "Sähköposti",
  "contactFormHelperText": "Anna sähköposti tai puhelinnumero *",
  "contactFormPhone": "Puhelinnumero",
  "contactFormOrganization": "Organisaatio (valinnainen)",
  "contactFormRole": "Roolisi (valinnainen)",
  "contactFormMessage": "Kirjoita viesti...",
  "contactFormSubmit": "Lähetä",
  "contactFormSuccessH1": "Kiitos yhteydenotosta!",
  "contactFormSuccessP": "Otamme sinuun yhteyttä vuorokauden sisällä",
  "contactFormSuccessB": "Sulje",

  "contactCompany": "Benete Oy",
  "contactAddress1": "Tykistökatu 4b",
  "contactAddress2": "20520 Turku, Suomi",
  "contactFloor": "(5. kerros)",
  "contactCeo": "Kari Bäckman, Toimitusjohtaja",
  "contactPhone": "+358 50 052 4514",
  "contactEmail": "kari.backman@benete.com",
  "contactHeadingIntro": "Jutellaan",
  "contactHeadingTitle": "Kuinka voimme auttaa?",
    
  "ideologyHeroSubtitle": "Hoitotyön asiantuntijana",
  "ideologyHeroTitle1": "Helpottaa arkea",
  "ideologyHeroTitle1b": "ja lisää turvallisuutta",
  "ideologyHeroTitle2": "Tuo mielen rauhaa",
  "ideologyHeroTitle2b": "perheille ja omaisille",
  "ideologyHeroTitle3": "Tukee ikäihmisten aktiivista",
  "ideologyHeroTitle3b": "ja vapaata elämää",
  "ideologyTitle": "Sinun ehdoillasi",

  "heroSubtitleLines": [
    [
      { "text": "Yksilöllinen", "color": "black" },
      { "text": "itsenäisyys", "color": "blue" }
    ],
    [
      { "text": "Digitaalinen", "color": "black" },
      { "text": "arvokkuus", "color": "blue" }
    ],
    [
      { "text": "Arvokas", "color": "black" },
      { "text": "elämä", "color": "blue" }
    ]
  ],
  "ideologyValuesCare": "Välittäminen",
  "ideologyValuesCareDesc": "Jokainen ihminen ansaitsee huomiota, lämpöä ja yksilöllistä hoivaa",
  "ideologyValuesSafety": "Turvallisuus",
  "ideologyValuesSafetyDesc": "Luotettava teknologia ja ympärivuorokautinen valvonta takaavat rauhan mielen",
  "ideologyValuesQuality": "Laatu",
  "ideologyValuesQualityDesc": "Sitoudumme korkeimpaan laatuun kaikessa tekemisessämme",

  "ideologySection1Title": "Oivalluksia päivittäisistä rutiineista",
  "ideologySection1P1": "Yksinkertaiset arkipäivän toiminnot luovat rytmin jokapäiväiseen elämäämme, kuten ruoan valmistus, lepo sekä hygieniasta huolehtiminen. Nämä ovat osa tavallista elämäämme, mutta niillä on myös ajateltua suurempi merkitys. Yhdistettynä ja analysoituna ne tuottavat arvokkaita havaintoja fyysisestä ja emotionaalisesta hyvinvoinnistamme.",
  "ideologySection1P2": "BeneCare palvelun avulla on mahdollista tunnistaa toimintakyvyssä ja kognitiossa tapahtuvia muutoksia jo aikaisessa vaiheessa. Yleisistä terveys- ja hyvinvointipalveluista poiketen analysoimme henkilön elämää kokonaisvaltaisesti kattaen paljon enemmän kuin pelkkiä fysiologisia tietoja.",

  "ideologySection2Title": "Elinympäristö",
  "ideologySection2P1": "Elinympäristöllä on tunnetusti suuri vaikutus hyvinvointiimme ja se voi myös kertoa paljon jokapäiväisestä elämästämme. Älyteknologioiden käyttö yleistyy jatkuvasti ja on vain ajan kysmys, kun kotimme ovat varustettuja moninaisilla sensoriteknologioilla mahdollistaen reaaliaikaisen elämän seuraamisen.",
  "ideologySection2P2": "BeneCare palvelun sofistikoituneet algoritmit tunnistavat ihmisen päivittäisiä toimintoja, mallintavat toimintatapoja tämän omassa elinympäristössä ja arvioivat toimintakyvyssä tapahtuvia mahdollisia muutoksia. Päivittäistä toimintaa havainnoimalla ja analysoimalla haitalliset muutokset toimintakyvyssä pystytään havaitsemaan paljon aikaisemmassa vaiheessa, kuin mitä tavanomaisten menetelmien avulla on mahdollista.",

  "ideologySection3Title": "Elinvoimainen ikääntyminen",
  "ideologySection3P1": "Elämänlaatu paranee kun henkilö voi toimia itsenäisesti omassa tutussa ympäristössä. Se luo turvallisuudentunnetta ja riippumattomuutta muista. Elinvoimaisen ikääntymisen perusta on oma aktiivisuus ja motivaatio elämään.",
  "ideologySection3P2": "Toimintakyvyn muutosten ja kognitiivisten häiriöiden varhainen tunnistaminen auttaa aikaisen ja täsmällisen hoidon tuottamisessa. Tällä on suuri vaikutus ihmisten elämään lisäten elämän aktiivisia ja itsenäisiä päiviä. Hellän huolenpidon mahdollistaminen ja itsenäisyyden tunteen vaaliminen ovat keskeisiä tavoitteitamme.",
  "ideologySection3P3": "Toimintamme tuloksena sosiaali- ja terveydenhuolto hyötyy merkittävästi alentuneista vanhusten hoitokustannuksista ja uusista tehokkaammista palveluista.",

  "ideologySection4Title": "OmaData",
  "ideologySection4P1": "Henkilöistä kerätty data on erittäin sensitiivistä. Palvelumme mahdollistaa asiakkaillemme täyden pääsyn ja kontrollin heidän omiin tietoihinsa. Palvelumme noudattaa uusimpia tietosuojan ja tietoturvallisuuden vaatimuksia huomioimalla nämä jo palvelujen suunnittelussa yhdessä meidän omien datan eettisten ja digitaalisen arvokkuuden periaatteiden kanssa.",

  "ideologySection5Title": "Arvomme",
  "ideologySection5P1": "Henkilökohtaisten toimintakyvyn muutoksia ei yleensä seurata tai kirjata ennen kuin on liian myöhäistä ja diagnoosi on annettu. Monet ihmiset ovat riippuvaisia toisista selvitäkseen päivästä mikä heikentää heidän itsenäisyyden tunnettansa. On tärkeää havaita mitä yksilöllinen itsenäisyys merkitsee jokaiselle.",
  "ideologySection5P2": "Palvelumme avulla on mahdollista tunnistaa toimintaan ja muistiin liittyviä häiriöitä mahdollisimman varhaisessa vaiheessa ja aloittaa tarvittavat hoitotoimenpiteet mahdollisimman aikaisin.",

  "benefitsTitle": "Hyödyt kaikille osapuolille",
  "benefitsSubtitle": "BeneCare parantaa hoitotyön laatua ja tukee ikäihmisten hyvinvointia",

  "benefitsCaregivers": "Hoitajille",
  "benefitsCaregivers1": "Tehokkaampaa ja mielekkäämpää hoitotyötä",
  "benefitsCaregivers2": "Aikaisempi puuttuminen ongelmiin",
  "benefitsCaregivers3": "Täsmällisempi vastaus asukkaiden tarpeisiin",
  "benefitsCaregivers4": "Ympärivuorokautinen turvallinen seuranta",

  "benefitsElderly": "Ikäihmisille",
  "benefitsElderly1": "Normaali arki ilman häiritseviä laitteita",
  "benefitsElderly2": "Ei puettavaa teknologiaa",
  "benefitsElderly3": "Parempi elämänlaatu",
  "benefitsElderly4": "Turvallisuuden tunne",

  "benefitsFamily": "Omaisille & Ammattilaisille",
  "benefitsFamily1": "Ajankohtainen tieto toimintakyvystä",
  "benefitsFamily2": "Varhaisessa vaiheessa olevien ongelmien havaitseminen",
  "benefitsFamily3": "Datan pohjalta tehdyt hoitopäätökset",
  "benefitsFamily4": "Läpinäkyvä raportointi",
    // Funding
  "fundingHorizonTitle": "Horizon 2020 tutkimus",
  "fundingHorizonText": "Benete Oy on saanut rahoitusta Euroopan unionin Horizon 2020 -tutkimus ja innovaatio-ohjelman avustussopimuksen Nro 877503 mukaisesti.",
  "fundingElyTitle": "ELY rahoitus",
  "fundingElyText": "Benete Oy on saanut rahoitusta Elinkeino-, liikenne- ja ympäristökeskukselta BNT-MDR hankkeeseen. Hankkeessa on kyseessä Benete Oy:n ikääntyneiden toimintakyvyn analysointipalvelun jatkokehitys.",

  "privacyTitle": "Tietosuojakäytäntö",
  "privacyCustomerInfoTitle": "Asiakastiedot",
  "privacyCustomerInfoContent": "Pysyäksemme yhteydessä nykyisiin tai potentiaalisiin asiakkaisiimme keräämme tietoja, joita annat ottaessasi meihin yhteyttä.",
  "privacyAnalyticsTitle": "Analytiikkapalvelut",
  "privacyAnalyticsContent": "Parantaaksemme vuorovaikutustasi verkkosivustomme kanssa voimme saada tietoa verkossa tapahtuvasta käyttäytymisestäsi ja käyttötiedoistasi. Emme yhdistä tältä verkkosivustolta kerättyjä tietoja mihinkään henkilökohtaisesti tunnistettaviin tietoihin muista lähteistä. Verkossa tapahtuva käyttäytymistieto poistetaan automaattisesti, jos se on yli 6 kuukautta vanhaa.",
  "privacyDataSecurityTitle": "Tietoturva",
  "privacyDataSecurityContent": "Noudattaen yleisesti hyväksyttyjä verkkotietoturvastandardeja olemme varmistaneet, että keräämämme henkilötiedot tallennetaan turvallisiin käyttöympäristöihin. Henkilötietoihisi pääsevät käsiksi vain henkilöt, joiden on käsiteltävä niitä työtehtäviensä suorittamiseksi.",
  "privacyAccessTitle": "Pääsy ja siirto ETA:n ulkopuolelle",
  "privacyAccessContent1": "Henkilökohtaisia tietojasi ei paljasteta tai myydä kolmansille osapuolille. Analytiikkapalveluiden kautta kerättyjä tietoja voidaan tallentaa Euroopan talousalueen ulkopuolelle, jos analytiikkapalvelun tai ohjelmiston tarjoaja tallentaa tiedot ETA:n ulkopuolelle. Muutoin emme säännöllisesti siirrä tietojasi Euroopan talousalueen ulkopuolelle.",
  "privacyAccessContent2": "Toteutamme aina vahvimmat meille saatavilla olevat oikeudelliset, menettelylliset, fyysiset ja tekniset toimenpiteet parantaaksemme anonymiteettiäsi ja välttääksemme tietojesi ei-toivotun paljastamisen muille henkilöille, yrityksille ja hallinnolle, ellei laki, oikeuselin tai valtion virasto vaadi meitä paljastamaan niitä.",
  "privacyUpdatesTitle": "Käytännön päivitykset",
  "privacyUpdatesContent": "Saatamme päivittää tätä tietosuojakäytäntöä ajoittain ja kannustamme sinua tarkistamaan uusimman version säännöllisesti osoitteessa www.benete.com. Pyrimme parhaaamme mukaan tiedottamaan sinulle kaikista tähän tietosuojakäytäntöön tehtävistä päivityksistä.",
  "privacyContactTitle": "Ota yhteyttä",
  "privacyContactContent": "Jos sinulla on kysyttävää tai haluat pyytää pääsyä, poistamista tai korjaamista antamiisi tietoihin, ota meihin yhteyttä osoitteessa privacy@benete.com.",

  "termsTitle": "Käyttöehdot",
  "termsIntroductionTitle": "Johdanto",
  "termsIntroductionContent": "Nämä käyttöehdot koskevat tämän verkkosivuston käyttöä; käyttämällä tätä verkkosivustoa hyväksyt nämä käyttöehdot kokonaisuudessaan. Jos olet eri mieltä näistä käyttöehdoista tai mistä tahansa osasta näitä käyttöehtoja, et saa käyttää tätä verkkosivustoa.",
  "termsIntellectualTitle": "Immateriaalioikeudet",
  "termsIntellectualContent": "Ellei toisin mainita, Benete Oy omistaa immateriaalioikeudet verkkosivustoon ja kaikkeen siinä julkaistuun materiaaliin (mukaan lukien mutta ei rajoittuen tekstiin, valokuviin ja muihin kuviin, tavaramerkkeihin ja logoihin).",
  "termsWarrantiesTitle": "Ei takuita",
  "termsWarrantiesContent1": "Tämä verkkosivusto tarjotaan \"sellaisena kuin se on\" ilman mitään edustuksia tai takuita, ilmaistuja tai oletettuja. Benete Oy ei anna mitään edustuksia tai takuita tähän verkkosivustoon tai tällä verkkosivustolla tarjottuihin tietoihin ja materiaaleihin liittyen.",
  "termsWarrantiesContent2": "Tällä verkkosivustolla olevat tiedot tarjotaan vain tiedotustarkoituksiin ja Benete Oy käyttää kohtuullista huolellisuutta ja taitoa varmistaakseen, että ne ovat oikein julkaisupäivänä. Mikään tällä verkkosivustolla ei ole, tai ole tarkoitettu olemaan, minkäänlaista neuvontaa. Benete Oy ei siksi hyväksy mitään vastuuta, joka aiheutuu verkkosivustolla tarjottuihin tietoihin luottamisesta minkään vierailijan tai kolmannen osapuolen toimesta, joka saattaa saada tietoa sen sisällöstä.",
  "termsLawTitle": "Laki ja lainkäyttövalta",
  "termsLawContent": "Näitä käyttöehtoja sääntelevät ja tulkitaan Suomen lain mukaisesti, ja kaikki näihin käyttöehtoihin liittyvät riidat kuuluvat Suomen tuomioistuinten yksinomaiseen toimivaltaan.",

  "cookieParagraph": "\"Hyväksyn evästeet\" -nappia painamalla hyväksyt, että evästeet tallennetaan laitteellesi. Näitä evästeitä käytetään tietojen keräämiseksi siitä, miten verkkosivustomme vierailijat käyttävät sivustoamme. Hyödynnämme kerättyä tietoa laatiaksemme yhteenvetoja ja kehittääksemme sivustoamme käyttäjäystävällisemmäksi.",
  "cookieTitle": "Evästekäytäntö",
  "cookieReadMore": "Lisätietoa",
  "cookieDecline": "Kieltäydy",
  "cookieAccept": "Hyväksy evästeet"
}