export default {
  "nav.home": "Hem",
  "nav.ideology": "Ideologi",
  "nav.service": "Tjänster",
  "nav.team": "Teamet",
  "nav.contact": "Kontakt",
  "header.title":"BeneCare",
  "header.subtitle": "Vi säkerställer att äldre får rätt vård i rätt tid.",
  "homepage.introduction_title":"Smart stöd för vårdarbete och vardagligt välbefinnande",
  "homepage.introduction_p1" : "BeneCare är utvecklat för vårdpersonal — inklusive personal inom äldrevård, sjuksköterskor, läkare och sjukgymnaster — samt privatanvändare som vill övervaka sina närståendes välbefinnande säkert och diskret.",
  "homepage.introduction_p2": "Tjänsten erbjuder dygnet-runt-övervakning utan bärbara enheter, vilket gör både professionell vård och vardagligt stöd mer effektivt och meningsfullt. BeneCare använder sensorteknik och intelligenta algoritmer för att modellera en persons dagliga rytm och beteende. ",
  "homepage.introduction_p3" :"Denna data hjälper till att upptäcka förändringar i hälsa, välbefinnande, funktionsförmåga och kognition — vilket möjliggör snabba åtgärder innan akut vård behövs.",
  "service.privacyTitle": "Vi håller personuppgifter säkra",
  "service.privacyText": "Analyserna som produceras av BeneCare-tjänsten är tillgängliga för senioren, deras anhöriga och vårdpersonal via webbtjänsten eller som utskrifter. Användningen av tjänsten och datainsamlingen baseras alltid på personens samtycke. Insamlade personuppgifter används eller överförs inte för något annat syfte än relaterat till användningen av tjänsten. I enlighet med dataskyddslagen har senioren rätt till sina egna personuppgifter och kan när som helst begära radering av sina personuppgifter eller avslutande av tjänsten.",
    
  "selector.title": "Välj kundtyp",
  "selector.subtitle": "Vi skräddarsyr våra tjänster efter dina behov",
  "selector.private.title": "Privatkunder",
  "selector.private.description": "Säkra din närståendes välbefinnande och övervakning hemma",
  "selector.company.title": "Företagskunder",
  "selector.company.description": "Förbättra vårdeffektiviteten och höj servicekvaliteten",
  "common.readMore":"Läs mer",
  "readMore.description":"Läs mer om våra tjänster och hur vi erbjuder ett unikt sätt att analysera livet.",
   // Carousel
    "carousel.elderly.title": "Säkert dagligt liv för äldre",
    "carousel.elderly.desc": "BeneCare stöder självständigt boende och ger en känsla av trygghet i vardagen.",
    "carousel.family.title": "Sinnesro för familjer",
    "carousel.family.desc": "Familjer kan övervaka sina närståendes välbefinnande och få uppdaterad information om deras hälsa.",
    "carousel.nurse.title": "Professionellt vårdarbete",
    "carousel.nurse.desc": "Vårdpersonal får exakt information om invånares funktionsförmåga och kan svara snabbt på förändringar.",
    "carousel.assistant.title": "Smart teknikassistans",
    "carousel.assistant.desc": "BeneCare-systemet tillhandahåller en lättanvänd plattform för att hantera och analysera all information.",
    // service
    "service.heading.intro": "Funktionsbedömning",
    "service.heading.title": "BeneCare",
    "features.title": "Vad övervakar BeneCare?",
    "features.subtitle": "Vår tjänst tillhandahåller kontinuerligt uppdaterad information om en persons funktionsförmåga och välbefinnande",
    "features.activity.title": "Aktivitetsövervakning",
    "features.activity.desc": "Tid i rum, inomhus- och utomhusrörelse, dagliga aktivitetsnivåer",
    "features.sleep.title": "Sömnkvalitet",
    "features.sleep.desc": "Mängd, kvalitet och timing av sömn och vila. Förändringar i nattligt beteende",
    "features.hygiene.title": "Hygienövervakning",
    "features.hygiene.desc": "Dusch- och handfatanvändning. Identifiering av förändringar i hygienvård",
    "features.wc.title": "Toalettbesök",
    "features.wc.desc": "Antal, timing och varaktighet av toalettbesök. Upptäckt av ökad frekvens",
    "features.health.title": "Hälsomått",
    "features.health.desc": "Vikt, BMI, blodtryck och andra hälsomått integrerade i systemet",
    "features.alerts.title": "Larm",
    "features.alerts.desc": "Nödarmband för omedelbar hjälp. Alla händelser loggas i systemet",
    // How It Works
    "how.title": "Hur fungerar BeneCare?",
    "how.subtitle": "En enkel och effektiv process som inte kräver någon åtgärd från individen",
    "how.step1.title": "Installation",
    "how.step1.desc": "Diskreta sensorer installeras i personens hem utan att störa det dagliga livet",
    "how.step2.title": "Datainsamling",
    "how.step2.desc": "Sensorer samlar automatiskt information om dagliga aktiviteter",
    "how.step3.title": "Analys",
    "how.step3.desc": "Sofistikerade algoritmer identifierar aktiviteter och modellerar beteendemönster",
    "how.step4.title": "Rapportering",
    "how.step4.desc": "Vårdgivare, läkare och familjemedlemmar får uppdaterad information om funktionsförmåga",
    // Private Customer Page
    "private.hero.title": "Säkra din närståendes välbefinnande",
    "private.hero.subtitle": "BeneCare tillhandahåller diskret övervakning och säkerhet för äldre som bor hemma",
    "private.hero.cta": "Kontakta oss",
    "private.benefits.title": "Varför BeneCare för privatkunder?",
    "private.benefits.peace.title": "Sinnesro",
    "private.benefits.peace.text": "Du kan lita på att din närstående är säker med 24/7 övervakning",
    "private.benefits.safety.title": "Säkerhet",
    "private.benefits.safety.text": "Automatiskt larm vid exceptionella situationer - hjälpen kommer i tid",
    "private.benefits.response.title": "Snabb respons",
    "private.benefits.response.text": "Omedelbar avisering om potentiella problem till familj och vårdgivare",
    "private.benefits.family.title": "Familjestöd",
    "private.benefits.family.text": "Hela familjen kan enkelt övervaka sin närståendes välbefinnande",
    
    // Company Customer Page
    "company.hero.title": "Förbättra vårdeffektiviteten",
    "company.hero.subtitle": "BeneCare hjälper vårdproffs att arbeta mer effektivt och förbättra servicekvaliteten",
    "company.hero.cta": "Begär offert",
    "company.benefits.title": "Varför BeneCare för företag?",
    "company.benefits.efficiency.title": "Effektivitet",
    "company.benefits.efficiency.text": "Minska onödiga besök och optimera arbetspass",
    "company.benefits.cost.title": "Kostnadsbesparingar",
    "company.benefits.cost.text": "Betydande besparingar i personalkostnader",
    "company.benefits.quality.title": "Kvalitetsfördel",
    "company.benefits.quality.text": "Förbättra servicekvaliteten med realtidsinformation",
    "company.benefits.data.title": "Datadriven",
    "company.benefits.data.text": "Fatta beslut baserade på tillförlitlig data",
    //Contact
    "contact.form.title": "Kontakta oss",
    "contact.form.type": "Jag är intresserad av:",
    "contact.form.type.general": "Allmän kontakt",
    "contact.form.type.assessment": "Funktionsbedömning",
    "contact.form.firstName": "Förnamn",
    "contact.form.lastName": "Efternamn",
    "contact.form.email": "E-post",
    "contact.form.phone": "Telefonnummer (valfritt)",
    "contact.form.organization": "Organisation (valfritt)",
    "contact.form.role": "Din roll (valfritt)",
    "contact.form.message": "Skriv ditt meddelande...",
    "contact.form.submit": "Skicka",
    "contact.form.successH1": "Tack för att du kontaktade oss!",
    "contact.form.successP": "Vi återkommer till dig inom 24 timmar",
    "contact.form.successB": "Stäng",
    "contact.company": "Benete Oy",
    "contact.address1": "Artillerigatan 4b",
    "contact.address2": "20520 Åbo, Finland",
    "contact.floor": "(5:e våningen)",
    "contact.ceo": "Kari Bäckman, Verkställande direktör",
    "contact.phone": "+358 50 052 4514",
    "contact.email": "kari.backman@benete.com",
    "contact.heading.intro": "Låt oss prata",
    "contact.heading.title": "Hur kan vi hjälpa till?",

  // Ideology Page
    "ideology.hero.subtitle": "Som vårdexpert",
    "ideology.hero.title1": "Förenklar vardagen",
    "ideology.hero.title1b": "och ökar tryggheten",
    "ideology.hero.title2": "Ger sinnesro",
    "ideology.hero.title2b": "till familjer och anhöriga",
    "ideology.hero.title3": "Stödjer aktivt",
    "ideology.hero.title3b": "och självständigt boende för äldre",
    
    "ideology.values.care": "Omsorg",
    "ideology.values.careDesc": "Varje person förtjänar uppmärksamhet, värme och individualiserad vård",
    "ideology.values.safety": "Säkerhet",
    "ideology.values.safetyDesc": "Pålitlig teknologi och övervakning dygnet runt garanterar sinnesro",
    "ideology.values.quality": "Kvalitet",
    "ideology.values.qualityDesc": "Vi är engagerade i högsta kvalitet i allt vi gör",
    "ideology.section1.title": "Insikter från dagliga rutiner",
    "ideology.section1.p1": "Enkla dagliga aktiviteter skapar rytmen i vårt vardagliga liv, såsom matlagning, vila och personlig hygien. Dessa är en del av vårt normala liv, men de har också en större betydelse än vi tror. Kombinerade och analyserade ger de värdefulla insikter om vårt fysiska och emotionella välbefinnande.",
    "ideology.section1.p2": "Med BeneCare-tjänsten är det möjligt att identifiera förändringar i funktionsförmåga och kognition i ett tidigt skede. Till skillnad från allmänna hälso- och välbefinnandetjänster analyserar vi en persons liv holistiskt och täcker mycket mer än bara fysiologisk data.",
    "ideology.section2.title": "Livsmiljö",
    "ideology.section2.p1": "Livsmiljön har känt stor påverkan på vårt välbefinnande och kan också berätta mycket om vårt dagliga liv. Användningen av smarta teknologier ökar ständigt och det är bara en tidsfråga innan våra hem är utrustade med olika sensorteknologier som möjliggör realtidsövervakning av livet.",
    "ideology.section2.p2": "BeneCare-tjänstens sofistikerade algoritmer känner igen en persons dagliga aktiviteter, modellerar beteenden i deras egen livsmiljö och bedömer möjliga förändringar i funktionsförmåga. Genom att observera och analysera dagliga aktiviteter kan skadliga förändringar i funktionsförmåga upptäckas i ett mycket tidigare skede än vad som är möjligt med konventionella metoder.",
    "ideology.section3.title": "Aktivt åldrande",
    "ideology.section3.p1": "Livskvaliteten förbättras när en person kan fungera självständigt i sin egen välbekanta miljö. Det skapar en känsla av trygghet och oberoende från andra. Grunden för aktivt åldrande är egen aktivitet och motivation för livet.",
    "ideology.section3.p2": "Tidig identifiering av förändringar i funktionsförmåga och kognitiva störningar hjälper till att tillhandahålla tidig och precis vård. Detta har stor påverkan på människors liv och lägger till aktiva och oberoende dagar i livet. Att möjliggöra mild omsorg och vårda känslan av oberoende är våra huvudmål.",
    "ideology.section3.p3": "Som ett resultat av vår verksamhet gynnas sociala och hälsovården avsevärt av minskade vårdkostnader för äldre och nya, mer effektiva tjänster.",
    "ideology.section4.title": "MinData",
    "ideology.section4.p1": "Data som samlas in från individer är extremt känslig. Vår tjänst gör det möjligt för våra kunder att ha full tillgång och kontroll över sina egna data. Vår tjänst följer de senaste kraven på dataskydd och informationssäkerhet och tar hänsyn till dessa redan i utformningen av tjänster, tillsammans med våra egna etiska data- och digitala värdighets principer.",
    "ideology.section5.title": "Våra värderingar",
    "ideology.section5.p1": "Personliga förändringar i funktionsförmåga övervakas eller registreras vanligtvis inte förrän det är för sent och en diagnos har ställts. Många människor är beroende av andra för att klara dagen, vilket försvagar deras känsla av oberoende. Det är viktigt att inse vad individuellt oberoende betyder för varje person.",
    "ideology.section5.p2": "Med vår tjänst är det möjligt att identifiera funktionella och minnesrelaterade störningar så tidigt som möjligt och påbörja nödvändiga behandlingsåtgärder så tidigt som möjligt.",
 
    // Benefits
    "benefits.title": "Fördelar för alla parter",
    "benefits.subtitle": "BeneCare förbättrar vårdens kvalitet och stöder äldres välbefinnande",
    "benefits.caregivers": "För vårdgivare",
    "benefits.caregivers.1": "Mer effektivt och meningsfullt vårdarbete",
    "benefits.caregivers.2": "Tidigare intervention vid problem",
    "benefits.caregivers.3": "Mer exakt respons på invånares behov",
    "benefits.caregivers.4": "24/7 säker övervakning",
    "benefits.elderly": "För äldre",
    "benefits.elderly.1": "Normalt dagligt liv utan påträngande enheter",
    "benefits.elderly.2": "Ingen bärbar teknik",
    "benefits.elderly.3": "Bättre livskvalitet",
    "benefits.elderly.4": "Känsla av trygghet",
    "benefits.family": "För familjer och professionella",
    "benefits.family.1": "Uppdaterad information om funktionsförmåga",
    "benefits.family.2": "Tidig upptäckt av uppkommande problem",
    "benefits.family.3": "Datadrivna vårdbeslut",
    "benefits.family.4": "Transparent rapportering",

};