export default {
   "navHome": "Hem",
  "navIdeology": "Ideologi",
  "navService": "Tjänster",
  "navSupport": "Support",
  "navContact": "Kontakt",

  "headerTitle": "BeneCare",
  "headerSubtitle": "Vi säkerställer att äldre får rätt vård i rätt tid.",

  "homepageIntroductionTitle": "Smart stöd för vårdarbete och vardagligt välbefinnande",
  "homepageIntroductionP1": "BeneCare är utvecklat för vårdpersonal inklusive personal inom äldrevård, sjuksköterskor, läkare och sjukgymnaster samt privatanvändare som vill övervaka sina närståendes välbefinnande säkert och diskret.",
  "homepageIntroductionP2": "Tjänsten erbjuder dygnet-runt-övervakning utan bärbara enheter, vilket gör både professionell vård och vardagligt stöd mer effektivt och meningsfullt. BeneCare använder sensorteknik och intelligenta algoritmer för att modellera en persons dagliga rytm och beteende.",
  "homepageIntroductionP3": "Denna data hjälper till att upptäcka förändringar i hälsa, välbefinnande, funktionsförmåga och kognition vilket möjliggör snabba åtgärder innan akut vård behövs.",

  "servicePrivacyTitle": "Vi håller personuppgifter säkra",
  "servicePrivacyText": "Analyserna som produceras av BeneCare-tjänsten är tillgängliga för senioren, deras anhöriga och vårdpersonal via webbtjänsten eller som utskrifter. Användningen av tjänsten och datainsamlingen baseras alltid på personens samtycke. Insamlade personuppgifter används eller överförs inte för något annat syfte än relaterat till användningen av tjänsten. I enlighet med dataskyddslagen har senioren rätt till sina egna personuppgifter och kan när som helst begära radering av sina personuppgifter eller avslutande av tjänsten.",

  "selectorTitle": "Välj kundtyp",
  "selectorSubtitle": "Vi skräddarsyr våra tjänster efter dina behov",
  "selectorPrivateTitle": "Privatkunder",
  "selectorPrivateDescription": "Säkra din närståendes välbefinnande och övervakning hemma",
  "selectorCompanyTitle": "Företagskunder",
  "selectorCompanyDescription": "Förbättra vårdeffektiviteten och höj servicekvaliteten",

  "commonReadMore": "Läs mer",
  "readMoreDescription": "Läs mer om våra tjänster och hur vi erbjuder ett unikt sätt att analysera livet.",

  "footerPrivacy": "Integritetspolicy",
  "footerTerms": "Villkor",

  "carouselElderlyTitle": "Säkert dagligt liv för äldre",
  "carouselElderlyDesc": "BeneCare stöder självständigt boende och ger en känsla av trygghet i vardagen.",
  "carouselFamilyTitle": "Sinnesro för familjer",
  "carouselFamilyDesc": "Familjer kan övervaka sina närståendes välbefinnande och få uppdaterad information om deras hälsa.",
  "carouselNurseTitle": "Professionellt vårdarbete",
  "carouselNurseDesc": "Vårdpersonal får exakt information om invånares funktionsförmåga och kan svara snabbt på förändringar.",
  "carouselAssistantTitle": "Smart teknikassistans",
  "carouselAssistantDesc": "BeneCare-systemet tillhandahåller en lättanvänd plattform för att hantera och analysera all information.",

  "serviceHeadingIntro": "Funktionsbedömning",
  "serviceHeadingTitle": "BeneCare",

  "featuresTitle": "Vad övervakar BeneCare?",
  "featuresSubtitle": "Vår tjänst tillhandahåller kontinuerligt uppdaterad information om en persons funktionsförmåga och välbefinnande",
  "featuresActivityTitle": "Aktivitetsövervakning",
  "featuresActivityDesc": "Tid i rum, inomhus- och utomhusrörelse, dagliga aktivitetsnivåer",
  "featuresSleepTitle": "Sömnkvalitet",
  "featuresSleepDesc": "Mängd, kvalitet och timing av sömn och vila. Förändringar i nattligt beteende",
  "featuresHygieneTitle": "Hygienövervakning",
  "featuresHygieneDesc": "Dusch- och handfatanvändning. Identifiering av förändringar i hygienvård",
  "featuresWcTitle": "Toalettbesök",
  "featuresWcDesc": "Antal, timing och varaktighet av toalettbesök. Upptäckt av ökad frekvens",
  "featuresHealthTitle": "Hälsomått",
  "featuresHealthDesc": "Vikt, BMI, blodtryck och andra hälsomått integrerade i systemet",
  "featuresAlertsTitle": "Larm",
  "featuresAlertsDesc": "Nödarmband för omedelbar hjälp. Alla händelser loggas i systemet",
    // How It Works
   "howTitle": "Hur fungerar BeneCare?",
  "howSubtitle": "En enkel och effektiv process som inte kräver någon åtgärd från individen",
  "howStep1Title": "Installation",
  "howStep1Desc": "Diskreta sensorer installeras i personens hem utan att störa det dagliga livet",
  "howStep2Title": "Datainsamling",
  "howStep2Desc": "Sensorer samlar automatiskt information om dagliga aktiviteter",
  "howStep3Title": "Analys",
  "howStep3Desc": "Sofistikerade algoritmer identifierar aktiviteter och modellerar beteendemönster",
  "howStep4Title": "Rapportering",
  "howStep4Desc": "Vårdgivare, läkare och familjemedlemmar får uppdaterad information om funktionsförmåga",

  "privateHeroTitle": "Säkra din närståendes välbefinnande",
  "privateHeroSubtitle": "BeneCare tillhandahåller diskret övervakning och säkerhet för äldre som bor hemma",
  "privateHeroCta": "Kontakta oss",
  "privateBenefitsTitle": "Varför BeneCare för privatkunder?",
  "privateBenefitsPeaceTitle": "Sinnesro",
  "privateBenefitsPeaceText": "Du kan lita på att din närstående är säker med 24/7 övervakning",
  "privateBenefitsSafetyTitle": "Säkerhet",
  "privateBenefitsSafetyText": "Automatiskt larm vid exceptionella situationer - hjälpen kommer i tid",
  "privateBenefitsResponseTitle": "Snabb respons",
  "privateBenefitsResponseText": "Omedelbar avisering om potentiella problem till familj och vårdgivare",
  "privateBenefitsFamilyTitle": "Familjestöd",
  "privateBenefitsFamilyText": "Hela familjen kan enkelt övervaka sin närståendes välbefinnande",

  "companyHeroTitle": "Förbättra vårdeffektiviteten",
  "companyHeroSubtitle": "BeneCare hjälper vårdproffs att arbeta mer effektivt och förbättra servicekvaliteten",
  "companyHeroCta": "Begär offert",
  "companyBenefitsTitle": "Varför BeneCare för företag?",
  "companyBenefitsEfficiencyTitle": "Effektivitet",
  "companyBenefitsEfficiencyText": "Minska onödiga besök och optimera arbetspass",
  "companyBenefitsCostTitle": "Kostnadsbesparingar",
  "companyBenefitsCostText": "Betydande besparingar i personalkostnader",
  "companyBenefitsQualityTitle": "Kvalitetsfördel",
  "companyBenefitsQualityText": "Förbättra servicekvaliteten med realtidsinformation",
  "companyBenefitsDataTitle": "Datadriven",
  "companyBenefitsDataText": "Fatta beslut baserade på tillförlitlig data",
    //Contact
   "contactFormTitle": "Kontakta oss",
  "contactFormType": "Jag är intresserad av:",
  "contactFormTypeGeneral": "Allmän kontakt",
  "contactFormTypeAssessment": "Funktionsbedömning",
  "contactFormFirstName": "Förnamn",
  "contactFormLastName": "Efternamn",
  "contactFormHelperText": "Ange e‑post eller telefonnummer *",
  "contactFormEmail": "E-post",
  "contactFormPhone": "Telefonnummer",
  "contactFormOrganization": "Organisation (valfritt)",
  "contactFormRole": "Din roll (valfritt)",
  "contactFormMessage": "Skriv ditt meddelande...",
  "contactFormSubmit": "Skicka",
  "contactFormSending": "Skickar…",
  "contactFormError": "Misslyckades att skicka meddelandet. Försök igen.",
  "contactFormSuccessH1": "Tack för att du kontaktade oss!",
  "contactFormSuccessP": "Vi återkommer till dig inom 24 timmar",
  "contactFormSuccessB": "Stäng",

  "contactCompany": "Benete Oy",
  "contactAddress1": "Artillerigatan 4b",
  "contactAddress2": "20520 Åbo, Finland",
  "contactFloor": "(5:e våningen)",
  "contactCeo": "Kari Bäckman, Verkställande direktör",
  "contactPhone": "+358 50 052 4514",
  "contactEmail": "kari.backman@benete.com",
  "contactHeadingIntro": "Låt oss prata",
  "contactHeadingTitle": "Hur kan vi hjälpa till?",

  "footerFollowUs": "Följ oss",
  
  "ideologySubtitleLine1a": "Individuell",
  "ideologySubtitleLine1b": "självständighet",
  "ideologySubtitleLine2a": "Digital",
  "ideologySubtitleLine2b": "värdighet",
  "ideologySubtitleLine3a": "Värdefullt",
  "ideologySubtitleLine3b": "liv",

  "ideologyHeroSubtitle": "Som vårdexpert",
  "ideologyHeroTitle1": "Förenklar vardagen",
  "ideologyHeroTitle1b": "och ökar tryggheten",
  "ideologyHeroTitle2": "Ger sinnesro",
  "ideologyHeroTitle2b": "till familjer och anhöriga",
  "ideologyHeroTitle3": "Stödjer aktivt",
  "ideologyHeroTitle3b": "och självständigt boende för äldre",
  "ideologyTitle": "På dina villkor",

  
  "ideologyValuesCare": "Omsorg",
  "ideologyValuesCareDesc": "Varje person förtjänar uppmärksamhet, värme och individualiserad vård",
  "ideologyValuesSafety": "Säkerhet",
  "ideologyValuesSafetyDesc": "Pålitlig teknologi och övervakning dygnet runt garanterar sinnesro",
  "ideologyValuesQuality": "Kvalitet",
  "ideologyValuesQualityDesc": "Vi är engagerade i högsta kvalitet i allt vi gör",

  "ideologySection1Title": "Insikter från dagliga rutiner",
  "ideologySection1P1": "Enkla dagliga aktiviteter skapar rytmen i vårt vardagliga liv, såsom matlagning, vila och personlig hygien. Dessa är en del av vårt normala liv, men de har också en större betydelse än vi tror. Kombinerade och analyserade ger de värdefulla insikter om vårt fysiska och emotionella välbefinnande.",
  "ideologySection1P2": "Med BeneCare-tjänsten är det möjligt att identifiera förändringar i funktionsförmåga och kognition i ett tidigt skede. Till skillnad från allmänna hälso- och välbefinnandetjänster analyserar vi en persons liv holistiskt och täcker mycket mer än bara fysiologisk data.",

  "ideologySection2Title": "Livsmiljö",
  "ideologySection2P1": "Livsmiljön har känt stor påverkan på vårt välbefinnande och kan också berätta mycket om vårt dagliga liv. Användningen av smarta teknologier ökar ständigt och det är bara en tidsfråga innan våra hem är utrustade med olika sensorteknologier som möjliggör realtidsövervakning av livet.",
  "ideologySection2P2": "BeneCare-tjänstens sofistikerade algoritmer känner igen en persons dagliga aktiviteter, modellerar beteenden i deras egen livsmiljö och bedömer möjliga förändringar i funktionsförmåga. Genom att observera och analysera dagliga aktiviteter kan skadliga förändringar i funktionsförmåga upptäckas i ett mycket tidigare skede än vad som är möjligt med konventionella metoder.",

  "ideologySection3Title": "Aktivt åldrande",
  "ideologySection3P1": "Livskvaliteten förbättras när en person kan fungera självständigt i sin egen välbekanta miljö. Det skapar en känsla av trygghet och oberoende från andra. Grunden för aktivt åldrande är egen aktivitet och motivation för livet.",
  "ideologySection3P2": "Tidig identifiering av förändringar i funktionsförmåga och kognitiva störningar hjälper till att tillhandahålla tidig och precis vård. Detta har stor påverkan på människors liv och lägger till aktiva och oberoende dagar i livet. Att möjliggöra mild omsorg och vårda känslan av oberoende är våra huvudmål.",
  "ideologySection3P3": "Som ett resultat av vår verksamhet gynnas sociala och hälsovården avsevärt av minskade vårdkostnader för äldre och nya, mer effektiva tjänster.",

  "ideologySection4Title": "MinData",
  "ideologySection4P1": "Data som samlas in från individer är extremt känslig. Vår tjänst gör det möjligt för våra kunder att ha full tillgång och kontroll över sina egna data. Vår tjänst följer de senaste kraven på dataskydd och informationssäkerhet och tar hänsyn till dessa redan i utformningen av tjänster, tillsammans med våra egna etiska data- och digitala värdighets principer.",

  "ideologySection5Title": "Våra värderingar",
  "ideologySection5P1": "Personliga förändringar i funktionsförmåga övervakas eller registreras vanligtvis inte förrän det är för sent och en diagnos har ställts. Många människor är beroende av andra för att klara dagen, vilket försvagar deras känsla av oberoende. Det är viktigt att inse vad individuellt oberoende betyder för varje person.",
  "ideologySection5P2": "Med vår tjänst är det möjligt att identifiera funktionella och minnesrelaterade störningar så tidigt som möjligt och påbörja nödvändiga behandlingsåtgärder så tidigt som möjligt.",
 //support
  "supportHeader": "BeneCare",
  "supportIntro": "Behöver du hjälp? Vårt supportteam säkerställer att din Benete‑tjänst fungerar smidigt varje dag.",
  "supportTitle": "Supportvideor",
  "supportSubtitle": "Titta på instruktionsvideor för att lära dig hur du använder BeneCare-tjänsten och löser vanliga problem.",
  "PIR1Title": "PIR 1-sensor",
  "PIR1Intro": "Installeras ovanför dörrkarmen för att övervaka rörelse i rummet. Säkerställer tillförlitlig detektering av närvaro och aktivitet.",
  "PIR2Title": "PIR 2-sensor",
  "PIR2Intro": "Takmonterad sensor som registrerar rörelse över ett större område och ger heltäckande rumsövervakning.",
  "RouterTitle": "Router",
  "RouterIntro": "Säkerställer stabil uppkoppling och tillförlitlig drift av alla sensorer. Bör placeras nära ett eluttag.",
  "AM6Title": "AM-6-sensor",
  "AM6Intro": "Monteras på ytan av en hushållsapparat för att registrera och följa användningsmönster.",
  "AR1Title": "AR-1-sensor",
  "AR1Intro": "Installeras på dörr och dörrkarm med ett maximalt avstånd på 1 cm mellan delarna. Registrerar när dörren öppnas eller stängs och indikerar in- och utpassering.",
  "TP10Title": "TP-10-sensor",
  "TP10Intro": "Installeras på duschens vattenrör för att övervaka vattenanvändning och duschaktivitet.",
  "SafetyBraceletTitle": "Trygghetsarmband",
  "SafetyBraceletIntro": "Bärs bekvämt runt handleden. När den röda knappen trycks skickas ett larm till en förvald kontakt vid nödsituation.",
  "SleepMonitorTitle": "Sömnmonitor",
  "SleepMonitorIntro": "Placeras under madrassen i brösthöjd. Mäter sömnens längd och vilomönster. Bör placeras nära ett eluttag.",
  "SmartScaleTitle": "Smart våg",
  "SmartScaleIntro": "Används på ett stabilt och plant underlag. Mäter kroppsvikt och stödjer kontinuerlig hälsouppföljning.",
  "supportHelp": "Behöver du mer hjälp?",
  "supportHelpDescription": "Om du inte hittar svaret på din fråga i videorna, kontakta oss.",
  "supportContact": "Kontakta support",

  "benefitsTitle": "Fördelar för alla parter",
  "benefitsSubtitle": "BeneCare förbättrar vårdens kvalitet och stöder äldres välbefinnande",

  "benefitsCaregivers": "För vårdgivare",
  "benefitsCaregivers1": "Mer effektivt och meningsfullt vårdarbete",
  "benefitsCaregivers2": "Tidigare intervention vid problem",
  "benefitsCaregivers3": "Mer exakt respons på invånares behov",
  "benefitsCaregivers4": "24/7 säker övervakning",

  "benefitsElderly": "För äldre",
  "benefitsElderly1": "Normalt dagligt liv utan påträngande enheter",
  "benefitsElderly2": "Ingen bärbar teknik",
  "benefitsElderly3": "Bättre livskvalitet",
  "benefitsElderly4": "Känsla av trygghet",

  "benefitsFamily": "För familjer och professionella",
  "benefitsFamily1": "Uppdaterad information om funktionsförmåga",
  "benefitsFamily2": "Tidig upptäckt av uppkommande problem",
  "benefitsFamily3": "Datadrivna vårdbeslut",
  "benefitsFamily4": "Transparent rapportering",

  "fundingHorizonTitle": "Horizon 2020 forskning",
  "fundingHorizonText": "Benete Oy har erhållit finansiering från Europeiska unionens Horizon 2020 forsknings- och innovationsprogram enligt bidragsavtal nr 877503.",
  "fundingElyTitle": "ELY-finansiering",
  "fundingElyText": "Benete Oy har erhållit finansiering från Närings-, trafik- och miljöcentralen för projektet BNT-MDR. Projektet handlar om vidareutveckling av Benete Oy:s analystjänst för äldres funktionsförmåga.",


  "privacyTitle": "Integritetspolicy",
  "privacyCustomerInfoTitle": "Kundinformation",
  "privacyCustomerInfoContent": "För att hålla kontakten med våra nuvarande eller potentiella kunder samlar vi in information som du tillhandahåller när du kontaktar oss.",
  "privacyAnalyticsTitle": "Analystjänster",
  "privacyAnalyticsContent": "För att förbättra din interaktion med vår webbplats kan vi få information om ditt onlinebeteende och användningsdata. Vi kommer inte att associera någon data som samlas in från denna webbplats med någon personligt identifierande information från någon annan källa. Onlinebeteendedata raderas automatiskt om den är äldre än 6 månader.",
  "privacyDataSecurityTitle": "Datasäkerhet",
  "privacyDataSecurityContent": "I enlighet med allmänt accepterade onlinesäkerhetsstandarder har vi säkerställt att de personuppgifter vi samlar in lagras i säkra driftsmiljöer. Dina personuppgifter kan endast nås av personer som behöver behandla dem för att utföra sina arbetsuppgifter.",
  "privacyAccessTitle": "Åtkomst och överföring utanför EES",
  "privacyAccessContent1": "Din personliga information kommer inte att avslöjas eller säljas till tredje part. Information som samlas in genom analystjänster kan lagras utanför Europeiska ekonomiska samarbetsområdet om analystjänsten eller mjukvaruleverantören lagrar data utanför EES. Annars överför vi inte regelbundet dina uppgifter utanför Europeiska ekonomiska samarbetsområdet.",
  "privacyAccessContent2": "Vi kommer alltid att implementera de mest robusta juridiska, procedurella, fysiska och tekniska åtgärder som är tillgängliga för oss för att förbättra din anonymitet och undvika oönskad avslöjande av dina uppgifter till andra individer, företag och administrationer, såvida vi inte är skyldiga att avslöja det enligt lag, rättslig myndighet eller statlig myndighet.",
  "privacyUpdatesTitle": "Policyuppdateringar",
  "privacyUpdatesContent": "Vi kan periodiskt uppdatera denna integritetspolicy och uppmuntrar dig att regelbundet kontrollera den senaste versionen på www.benete.com. Vi kommer att göra vårt bästa för att informera dig om eventuella uppdateringar av denna integritetspolicy.",
  "privacyContactTitle": "Kontakta oss",
  "privacyContactContent": "Om du har några frågor eller vill begära åtkomst, borttagning eller korrigering av den information du har tillhandahållit, kontakta oss på privacy@benete.com.",

  "termsTitle": "Villkor",
  "termsIntroductionTitle": "Introduktion",
  "termsIntroductionContent": "Dessa villkor styr din användning av denna webbplats; genom att använda denna webbplats accepterar du dessa villkor i sin helhet. Om du inte håller med om dessa villkor eller någon del av dessa villkor får du inte använda denna webbplats.",
  "termsIntellectualTitle": "Immateriella rättigheter",
  "termsIntellectualContent": "Om inte annat anges äger Benete Oy de immateriella rättigheterna till webbplatsen och till allt material som publiceras på den (inklusive men inte begränsat till text, fotografier och andra bilder, varumärken och logotyper).",
  "termsWarrantiesTitle": "Inga garantier",
  "termsWarrantiesContent1": "Denna webbplats tillhandahålls \"som den är\" utan några representationer eller garantier, uttryckliga eller underförstådda. Benete Oy lämnar inga representationer eller garantier i förhållande till denna webbplats eller informationen och materialet som tillhandahålls på denna webbplats.",
  "termsWarrantiesContent2": "Informationen som finns på denna webbplats tillhandahålls endast i informationssyfte och Benete Oy kommer att använda rimlig omsorg och skicklighet för att säkerställa att den är korrekt vid publiceringsdatumet. Ingenting på denna webbplats utgör, eller är avsett att utgöra, råd av något slag. Benete Oy accepterar därför inget ansvar eller ansvar som uppstår från något förlitande på information som tillhandahålls på webbplatsen av någon besökare, eller av någon tredje part som kan informeras om något av dess innehåll.",
  "termsLawTitle": "Lag och jurisdiktion",
  "termsLawContent": "Dessa villkor kommer att regleras av och tolkas i enlighet med finsk lag, och alla tvister som rör dessa villkor kommer att vara föremål för den exklusiva jurisdiktionen hos domstolarna i Finland.",

  "cookieParagraph": "Genom att klicka på ”Tillåt cookies” samtycker du till att cookies lagras på din enhet. Detta förbättrar navigeringen på webbplatsen, möjliggör analys av användningen och stödjer våra marknadsföringsinsatser.",
  "cookieTitle": "Cookie policy",
  "cookieReadMore": "Lära sig mer",
  "cookieDecline": "Tillbakagång",
  "cookieAccept": "Tillåt cookies"

};